### ISSUE TITLE
Compare files / Output files

### ISSUE THREAD

**Issue by Shimon-Schocken** [nand2tetris/web-ide#154]
When the simulation is successful, the compare and output files should be exactly the same: Line numbers, column dividers (vertical bar characters), blank lines, etc.

By the way, some scripts do have blank lines. Is this intentional? To make them more readable?

**Comment by DavidSouther** [comment]
Is this not the case currently? The compare panel adds formatting and highlighting, but the underlying files (in memory) are otherwise identical. I did edit some scripts for readability when copying them from the course site to this repo.

**Comment by Shimon-Schocken** [comment]
They are the same contents wise, but not format wise. Let's talk about it in our next zoom meeting.

**Comment by DavidSouther** [comment]
This format was implemented at some point
