### ISSUE TITLE
Step / play / reset tooltips and icons

### ISSUE THREAD

**Issue by Shimon-Schocken** [nand2tetris/web-ide#164]
The "tooltips" of the step/play/reset buttons obscure the tab titles below them. Is there a way to cause the tooltips to pop up above the buttons?

The graphical icon of the "play" button is confusing. It suggests a single "step" action. I suggest replacing the current "play" icon with a "fast forward" icon (the graphical opposite of the current "reset" icon).

In the normal/fast/faster menu, I suggest replacing "normal" with "slow", and keeping it the default.

**Comment by DavidSouther** [comment]
> The "tooltips" of the step/play/reset buttons obscure the tab titles below them.

They do, but it should be only temporary (during hover). Most other elements also drop down on the page (the links, the select dropdowns, etc. For CSS technical reasons, putting them above the button is very difficult. For these reasons, I am not going to work on this in the near future.

> I suggest replacing the current "play" icon with a "fast forward" icon
> I suggest replacing "normal" with "slow"

Done, it looks much better!
<img width="254" alt="image" src="https://user-images.githubusercontent.com/498712/209441864-5653b3d1-805f-4297-a24c-fd6e6dce4b86.png">
