### ISSUE TITLE
Web IDE drops "Builtin" toggle switch during edge case

### ISSUE THREAD

**Issue by njkrichardson** [nand2tetris/web-ide#187]
Hi there, 

The following sequence of steps causes the "Builtin" toggle switch to disappear unless I reload the page: 
1. Select some chip
2. Toggle builtin ON 
3. Select another chip (before turning builtin OFF) 

At this point, the builtin toggle disappears altogether and does not reappear until the page is reloaded.

**Comment by DavidSouther** [comment]
Thanks for the bug report! A variation on this can also prevent changing the project selector.

**Comment by Shimon-Schocken** [comment]
Following up on this issue: The students will start working on Project 3 next week. If it will be fixed by then, great. If not, we'll notify them about the issue.

**Comment by DavidSouther** [comment]
This affects any project on the Chips page. I'll have time this afternoon to look into it.
