### ISSUE TITLE
[bug]: Web UI has disproportional sizes 

### ISSUE THREAD

**Issue by RaphGL** [nand2tetris/web-ide#229]
### Program

None

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

raphfl.dev@gmail.com

### What happened?

The sizes are disproportional affecting usability for all simulators on the web page. This started this friday (2024/02/09), I believe as it was working fine before then. 
![image](https://github.com/nand2tetris/web-ide/assets/28673457/4bd41a7a-a515-4978-874d-3371774d0112)

### Additional Comments

I've tested this on Chrome and Firefox on a Windows and Linux machine and I've also tried clearing cache just to be on the safe side here. 

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Thank you for the bug report. This was fixed over the weekend in https://github.com/nand2tetris/web-ide/pull/226. Please refresh (possibly after clearing your browser's cache) and confirm that the button sizes are restored to their expected size.

**Comment by RaphGL** [comment]
Yeah seems to be fixed now. I only created the issue cause it was still broken earlier today when I wrote this issue (the screenshot is from today). Thanks for the quick response :)

**Comment by DavidSouther** [comment]
Gotcha! Thanks again for filing it, must have been an issue with CDN rollint out slowly or the build running later than expected. We'll look into getting the auto push working more quickly.
