### ISSUE TITLE
[bug]: Bug report bugs

### ISSUE THREAD

**Issue by Shimon-Schocken** [nand2tetris/web-ide#266]
### Program

None

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

schocken@gmail.com

### What happened?

Erase the '(coming soon)' qualifiers from the Interface fields of this report.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Done
