### ISSUE TITLE
[feature]: Changing the order of some controls (usability impovement)

### ISSUE THREAD

**Issue by Shimon-Schocken** [nand2tetris/web-ide#287]
### Program

VM Emulator

### Interface

None

### What feature are you proposing?

The current horizontal order of the controls I am writing about is:

Key: bla Char code: bla Enable Keyboard

The order should be:

Enable Keyboard Key: bla Char code: bla 

Also: The blue margins of the Enable Keyboard button are a bit too wide. Please make them narrower.

### Do you want to try to add this feature?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Fixed in #289
