### ISSUE TITLE
[bug]: Eval broken on Firefox

### ISSUE THREAD

**Issue by Apitheia** [nand2tetris/web-ide#321]
### Program

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### What happened?

On Firefox 126.0, while editing a Chip, not using the Builtin, changing the Input pins and clicking Eval will clear input pins instead of displaying correct Output and Internal pins.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Thank you for the bug report. This should be fixed (you may need to refresh the page) - if it is not, please re-open and let us know!
