### ISSUE TITLE
Download button does not work in online editor[bug]: 

### ISSUE THREAD

**Issue by ananth521** [nand2tetris/web-ide#325]
### Program

None

### Interface

Website (https://nand2tetris.github.io/web-ide)

### What happened?

The Downoad button in online editor does not work.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
In chrome, I am able to download the project files:

<img width="632" alt="image" src="https://github.com/nand2tetris/web-ide/assets/498712/16d46b0e-a4d9-40d4-852f-a62b96f51f69">


You may be prompted to allow downloads, for instance, in Safari

<img width="541" alt="image" src="https://github.com/nand2tetris/web-ide/assets/498712/cab7e1c5-8fa1-4d9f-ae94-92d514e448b7">

after which the download completes.

<img width="519" alt="image" src="https://github.com/nand2tetris/web-ide/assets/498712/2f1a8573-3cd5-4823-ae66-44dcf86cf6e0">


It looks similar in Firefox:

<img width="814" alt="image" src="https://github.com/nand2tetris/web-ide/assets/498712/e98a09eb-20c6-4c2a-9529-20694d667b33">

**Comment by DavidSouther** [comment]
If you are able to reproduce this issue with steps or screenshots, please do re-open this ticket!
