### ISSUE TITLE
[feature]: Hardware simulator -- upload files

### ISSUE THREAD

**Issue by martybillingsley** [nand2tetris/web-ide#387]
### Tool

Hardware Simulator

### Interface

None

### What feature are you proposing?

The hardware simulator is currently limited to the files from projects 1-3 and 5. In order to implement and test a chip that is not part of those projects, you have to go to some pains to edit and overwrite the project files. 

I have my students implement additional chips, both as assignments and on exams. It's more difficult in the new software.

Would it be possible to allow upload of local .hdl, .tst, and .cmp files within in the hardware simulator?

### Do you want to try to add this feature?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Thank you for opening this issue! It's certainly a feature we intend to support, and we will prioritize it higher with this feedback. It's being tracked already at https://github.com/nand2tetris/web-ide/issues/352
