### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by martybillingsley** [nand2tetris/web-ide#398]
### Tool

CPU Emulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

mbilling@uchicago.edu

### What happened?

When running a student's fill program, the online CPU emulator didn't crash when it should have crashed 
because of a memory overrun. The standalone (old) CPU emulator does crash appropriately. 

In the program (attached), color_location is a variable used as a pointer to keep track of the next location in the screen RAM to be filled.  In the (BLACK) section of code, there is no check to see if color_location is still less than KBD before incrementing; this leads to the memory overrun.

Wondering why the online emulator doesn't crash, when it should. (Is this a feature??? 😀)

Program (remove the .txt extension -- had to add it to stop github complaining): 
[Fill.asm.txt](https://github.com/user-attachments/files/16152182/Fill.asm.txt)

Also, there is 32K of RAM in the CPU emulator, which doesn't match the 24K+1 RAM size we implemented in hardware. This is confusing to my students; is there a reason for it?

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
The memory size issue was brought up in #385, fixed in #388, and will be released soon. This might also "solve" your memory overrun issue - but not at 0x6000 (the KBD pointer), rather, at 0x6001 past the end of the entire memory.
