### ISSUE TITLE
[bug]: cli installation installs wrong package

### ISSUE THREAD

**Issue by kochaika** [nand2tetris/web-ide#400]
### Tool

General

### Interface

VSCode Extension (coming soon, or manually installed)

### What happened?

Hi!

Now in [README](https://github.com/nand2tetris/web-ide?tab=readme-ov-file#cli) there is a command for `cli` installation:

`npm run build && npm i -g cli`

This is expected to install the `cli` package from the `nand2tetris` project. In fact, by default, `npm` checks if this package is among the published ones. And it is. And it installs [this](https://github.com/node-js-libs/cli) package

It wasn't at all obvious to understand :)

Solution: specify the **path** to the package: `npm i -g ./cli`

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Great catch, thank you!
