### ISSUE TITLE
[bug]: Invalid memory access is tested

### ISSUE THREAD

**Issue by Reilithion** [nand2tetris/web-ide#404]
### Tool

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

reilithion+nand2tetris@gmail.com

### What happened?

The specification of Memory in Project 5 says that access to an address above 0x6000 is invalid (line 17 in the comment of the skeleton). But line 103 of projects/05/Memory.tst explicitly tests the student's implementation by accessing memory address 0x6234, expecting to get a zero. This test may fail on an otherwise correct implementation in practice if (as was the case in my implementation) the circuit outputs the keyboard input whenever bits 13 and 14 of the address are true and a key is being pressed on the keyboard at the time the test script runs line 103.

I propose this test should be removed. The way I read the specification, it sounds like the behavior of the Memory chip when the address is greater than 0x6000 is undefined, and therefore no test with an access of such an address should be included in the test script.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
>  the circuit outputs the keyboard input whenever bits 13 and 14 of the address

The Memory chip should only read keyboard on 0x6000. While reading >0x6000 is invalid for a Hack ASM program, the chip itself is still quite well defined, in that it reads 0.

Think back to chapter 3 while you were first implementing RAM chips. The suggested implementation is a bank of Registers wrapped with mux/demuxers. If one were to "leave out" half of the registers, as well has the WRITE-side muxers, the chip would still have the circuitry to read from the grounded (voltage-low) demuxer, which would read a 0. The test is correct that reading an invalid address in memory is defined, and defined as returning 0. I will make a slight update to the text of the chip description.
