### ISSUE TITLE
[bug]: CPU Emulator does not allow references using brackets and existing memory addresses

### ISSUE THREAD

**Issue by ynkze** [nand2tetris/web-ide#420]
### Tool

CPU Emulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### What happened?

CPU emulator does not allow use of brackets e.g. `(LOOP)` and reference to existing memory addresses e.g. `@SCREEN`.
When I upload a script that uses such references it works fine (though it automatically translates to existing line number instead), not sure if that is the intended behavior because it's very unfriendly to not be able to use these references on the IDE alone.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by netalondon** [comment]
Hi @ynkze, if you mean that you can't input values such as `(LOOP)` directly into the ROM, this is indeed intended.
Note that `(LOOP)` is just a symbol for the assembler to know what to substitute `@LOOP` for, not an actual instruction.
It gets omitted in the assembler process and doesn't take up any ROM space.

Generally, the CPU emulator is designed to run already assembled programs.
If you're looking to write and test assembly programs, I believe the tool you're looking for is the assembler.
In the assembler you can use the assembly language syntax freely, and when you're done you can translate your program and run it in the CPU emulator. 
(There is a designated button for this, no need to download and re-upload).

I hope this solves your issue.

I'm closing this for now but if this isn't what you meant feel free to reopen.
