### ISSUE TITLE
[bug]: 1-2 got 65535

### ISSUE THREAD

**Issue by ndNovaDev** [nand2tetris/web-ide#429]
### Tool

CPU Emulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### What happened?

```
@1
D=A
@0
M=D
@2
D=A
@0
D=M-D
```
the expected value of D is -1, but got 65535

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ndNovaDev** [comment]
```
@1
D=-A
```
the expected value of D is -1, but also got 65535

**Comment by netalondon** [comment]
Hi @ndNovaDev, 
`65535` is equivalent to `-1` using 2's complements, so this is actually the intended behavior.

If you feel there's more that needs to be said about this, feel free to reopen the issue.

**Comment by ndNovaDev** [comment]
oh sorry, it's my fault
