### ISSUE TITLE
[bug]: Hardware simulator compare file section flickering issue

### ISSUE THREAD

**Issue by Shimanshu83** [nand2tetris/web-ide#431]
### Tool

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

shimanshuyadav83@gmail.com

### What happened?

This is happening when I was doing Project 2 | ALU assignment. If you slide compare file section it start flickering. 
I have added a video for your reference.
[Screencast from 17-08-24 03:57:36 PM IST.webm](https://github.com/user-attachments/assets/71518543-5089-4ab3-aeef-6acab611ed27)

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Thank you for the screencast, however, I am unable to replicate this behavior. That said, I'm not sure what "slide compare file section" means, and it's not clear what behavior you're doing in the screenshot to get the stutter. That said, we have redesigned part of that toolbar. so if you remember what action you were taking for this video, and it's still happening, please re-open and provide clarification! Thank you!
