### ISSUE TITLE
[bug]: VM emulator skips a loop

### ISSUE THREAD

**Issue by happytomatoe** [nand2tetris/web-ide#446]
### Tool

None

### Interface

WebInterface

### What happened?

![Recording 2024-09-04 at 19 47 13](https://github.com/user-attachments/assets/fc2f9b88-e0e1-4257-bf4b-3502fbb98468)
Sample code
```
class Main {
  function void main() {
    while (true) {
      do Main.drawCloud(100);
      }
      return;
  }


  function void drawCloud(int location) {
    var int memAddress;
    let memAddress=16384 + location;
    do Memory.poke(memAddress+1, 448);
    do Memory.poke(memAddress+33, 1854);
    do Memory.poke(memAddress+65, 3075);
    do Memory.poke(memAddress+96, -32768);
    return;
  }
}
````
I am using Chromium Version 127.0.6533.99 (Official Build) Fedora Project (64-bit). I am also running web ide in incognito mode

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by happytomatoe** [comment]
nvm. I am running fibonacci sequence

**Comment by happytomatoe** [comment]
qq - is it possible to run Jack files in web ide? If yes how?

**Comment by netalondon** [comment]
You can compile your project using the Jack compiler and click the run button to load the compiled code to the VM emulator where you can run it.
