### ISSUE TITLE
[bug]: Jack compiler - page slides after using a slider and clicking on a tab when there are a lot of files  

### ISSUE THREAD

**Issue by happytomatoe** [nand2tetris/web-ide#451]
### Tool

None

### Interface

None

### What happened?

I have many files. When I use horizontal slider and click on last tab page slides
![Screenshot from 2024-09-11 09-41-27](https://github.com/user-attachments/assets/fe15144b-4fd2-429f-85b0-5115b5d0e1f5)

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Thank you for the bug report!

This can probably be approached by setting a max-width + horizontal scroll in https://github.com/nand2tetris/web-ide/blob/main/web/src/shell/tab.scss
