### ISSUE TITLE
[bug]: Typo in cmp file for mux4way16

### ISSUE THREAD

**Issue by kochaika** [nand2tetris/web-ide#453]
### Tool

Hardware Simulator

### Interface

None

### What happened?

Hi! Am I right thinking two vertical slash [here](https://github.com/nand2tetris/web-ide/blob/eb30f7148b0950e266a7bb9560b243becdc98f32/projects/src/project_01/11_mux4way16.ts#L9C104-L9C105) is a typo? It seems that the test fails in CLI mode because of this.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
@kochaika thank you for opening an issue!

@netalondon please take a look
