### ISSUE TITLE
[bug]: Running CPU Emulator in Fast Mode blocks the whole web application

### ISSUE THREAD

**Issue by fwoerister** [nand2tetris/web-ide#489]
### Tool

CPU Emulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

florian.woerister@univie.ac.at

### What happened?

Dear nand2tetris team,

I encountered an issue while running my Fill.asm program from Chapter 4. The CPU Emulator prompts me to set the speed to _Fast_ (as indicated in the status bar at the bottom of the emulator). However, when I do this, the entire web application becomes unresponsive during the emulation, resulting in lag and minimal input acceptance.

I am using Firefox 131.0.3 (aarch64) on macOS 15.0.1 (24A348).

To troubleshoot, I verified my script using the legacy Java-based CPU Emulator, where the program ran as expected without any performance issues.

Best regards,
Florian

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
This is an unfortunate reality of running in a predominantly single-threaded JavaScript environment. While the web IDE attempts to use requestAnimationFrame to maintain a consistent frame rate, at high simulation speeds the simulator will consistently take more than 16ms. Perhaps we can add an "adaptive" "fast" setting? We already record the time spent running a frame, so if, say, it takes longer than 8ms, the runner could reduce the step count for the next frame until it hits that point?
