### ISSUE TITLE
[bug]: Web IDE couldn't load '.hack' files in test scripts of projects/5/Computer.hdl

### ISSUE THREAD

**Issue by abhishekrathore** [nand2tetris/web-ide#490]
### Tool

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

rathore.abhishek87@gmail.com

### What happened?

Facing a bug when running the "projects/5/Computer.hdl" tests.
In the chrome console, it shows that 'Add.hack' or 'Max.hack' file is not loaded due to some exception.

![Screenshot 2024-10-17 at 7 30 22 PM](https://github.com/user-attachments/assets/fddc1f42-3240-42cf-bfd4-dd9a860dbf2f)

Digging deeper in source code found  that code is searching for file in '/samples/' directory NOT '/projects/5' directory.
Fixed it in the Chrome local storage and then it worked.

![Screenshot 2024-10-17 at 7 29 44 PM](https://github.com/user-attachments/assets/2c4f26f1-4a18-47f0-8f66-cbfdbe371335)

Its only for files with ".hack" extensions. I guess the '/samples' directory key in WEB IDE is not there by default.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fwoerister** [comment]
+1

I encountered the same error. Would be interesting if the hack files are loaded to the wrong directory or the ide is looking at the wrong location when loading hack files to the ROM.

**Comment by lyrakisk** [comment]
I also had the same problem. The quick fix that @abhishekrathore suggested solved it locally for me as well.

**Comment by EricOrrDev** [comment]
I am having same problem, working on a resolution for firefox users.

**Comment by DavidSouther** [comment]
This should be resolved now that #450  is merged and deployed.
