### ISSUE TITLE
[bug]: Extension not building

### ISSUE THREAD

**Issue by devregnfo** [nand2tetris/web-ide#491]
### Tool

General

### Interface

VSCode Extension (coming soon, or manually installed)

### Contact Details

devregnfo@gmail.com

### What happened?

I couldn't open the VSCode project, or build the extension by use of NPM.
Missing files I guess?

Thanks

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
I don't think anyone has worked on the VSCode extension in some time, it will need some updates to match changes to the project structure.
