### ISSUE TITLE
[bug]: web-ide link broken

### ISSUE THREAD

**Issue by devregnfo** [nand2tetris/web-ide#492]
### Tool

General

### Interface

None

### What happened?

It is not possible to run the web-ide locally (offline) because of broken link.
The link in the web folder isn't working.
Thanks

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
There are two ways to run the project from source

-  `npm run web` starts in devel mode, with hot reloading of components through react-scripts
- `npm run -w web serve-pwa` performs a full build and serves using a static HTTP server
