### ISSUE TITLE
[bug]: why is the syntax sel=sel[0..1] instead of sel=sel[1..0]?  I thought we could keep the MSD and LSD in the same place as how we write binary?

### ISSUE THREAD

**Issue by Dusk1087** [nand2tetris/web-ide#494]
### Tool

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### Contact Details

reedpfoster@gmail.com

### What happened?

A bug happened!  More of a question really

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Please open this in the "Discussions" section of the project, and I'll ask @Shimon-Schocken (an author of the textbook) to reply there!
