### ISSUE TITLE
[bug]: hdl sensitive to pin order

### ISSUE THREAD

**Issue by ylapidoth** [nand2tetris/web-ide#500]
### Tool

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### What happened?

From the forums, by [Will Marrero](http://nand2tetris-questions-and-answers-forum.52.s1.nabble.com/Hardware-simulator-is-sensitive-to-ordering-of-HDL-statements-td4037913.html):

> Appendix 2 of the book states that HDL statements can be reordered without affecting the chip's behavior, however the online hardware simulator tool seems to be sensitive to the ordering of statements.  I was having difficulty passing the tests for the CPU chip I implemented and was confused by the output that was generated.  By changing the order of the statements in the PARTS section, I was then able to pass the tests.

> A thread where I posted a screenshot of the simulator with what seems to be inconsistent output in the ALU visualizer can be found here: http://nand2tetris-questions-and-answers-forum.52.s1.nabble.com/Confused-with-simulator-output-on-CPU-td4037903.html

I'll add an example of my own, this is me trying to implement a mux chip:

![image](https://github.com/user-attachments/assets/7608a08b-dd9a-4d92-b65b-c35a3430a52e)

Notice the change in output with differently ordered statements:

![image](https://github.com/user-attachments/assets/40e0d226-80f5-419a-981c-6ef8513b4474)

### Additional Comments

Thank you so much for providing us these tools and this knowledge.

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Thank you for the bug report, however, I cannot replicate the issue with the current version. This should have been resolved as part of #360. Please re-open with additional test cases if you can verify it still persists.

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/949022fc-2afb-433d-8725-cd0887ed8222">
