### ISSUE TITLE
[bug]: Testing feature corrupt

### ISSUE THREAD

**Issue by gaga999** [nand2tetris/web-ide#503]
### Tool

Hardware Simulator

### Interface

Website (https://nand2tetris.github.io/web-ide)

### What happened?

The test feature of computer of project 5 on the website doesn't works. It didn't move at all after pressing the run button. 

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
This has been resolved in the update on 2024-11-27.
