### ISSUE TITLE
[bug]: VM Emulator shows error message "File name Main.vm doesn't match class name Main (at Main.main)" when uploading files

### ISSUE THREAD

**Issue by dorianignee** [nand2tetris/web-ide#530]
### Tool

None

### Interface

None

### What happened?

When uploading any local folder to the VM emulator, it shows an error message, stating that the file name doesn't match the class name.
![image](https://github.com/user-attachments/assets/22149664-8cc2-4283-9f80-da93b6c5a1fd)

### Additional Comments

The function validateFile() in simulator/src/vm/vm.ts checks if "Main" is equal to "Main.vm", what obviously isn't the case.

### Do you want to try to fix this bug?

- [X] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DavidSouther** [comment]
Feel free to open a PR with the fix(es) you'd like!
